### PR TITLE
Replace jquery code to native js

### PR DESCRIPTION
**Pull request by Fedik**
Replace jquery code to native js.
In theory `sa11y.js` already should work without jquery.

However we still need to update Example pages to Bootstrap 5, and remove jquery from there.

### CODE REVIEW

**Comment by brianteeman** [comment]
Thanks. Will check and merge after the grand prix

**Comment by brianteeman** [comment]
This is probably my complete js lack of knowledge but

I have a joomla test site for this with most of the examples for testing. https://a11y.brianstest.site

Currently its just got the original js all hard coded in the template as below and it works fine. 
```

<!-- Original Upstream code -->
	<!-- Latest jQuery (Bookmarklet uses jQuery slim build) -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.slim.min.js"></script>

	<!-- Tippy.js v6 CDN (tooltip library) -->
	<script src="https://unpkg.com/@popperjs/core@2"></script>
	<script src="https://unpkg.com/tippy.js@6"></script>

	<!-- Sa11y -->
	<link rel="stylesheet" href="templates/cassiopeia/sa11yjq/sa11y.css"/>
	<script src="templates/cassiopeia/sa11yjq/sa11y-english.js"></script>
	<script src="templates/cassiopeia/sa11yjq/sa11y.js"></script>
```

I've been trying to do the same with the js from this pr to  test it but no luck. I assume I am missing something obvious. No errors in the console but also nothing happening on screen

**Comment by Fedik** [comment]
Do this from my comment https://github.com/joomla-projects/joomla-a11y-checker/issues/16#issuecomment-966924098:
```html
<link rel="stylesheet" href="path-to/css/joomla-a11y-checker.css" />
<script src="https://unpkg.com/@popperjs/core@2" defer></script>
<script src="https://unpkg.com/tippy.js@6" defer></script>
<script src="path-to/js/joomla-a11y-checker.umd.js" defer></script>
<script src="path-to/js/lang/en.js" defer></script>
<script>
  document.addEventListener('DOMContentLoaded', function() {
     // Set translations
     Sa11y.Lang.addI18n(Sa11yLangEn.strings);

     // Instantiate
     const checker = new Sa11y.Sa11y(Sa11yLangEn.options);
  });
</script>
```

Later for Joomla we will have "setup.js" file, instead of inline code.

**Comment by brianteeman** [comment]
almost. script seems to be working perfectly without jquery 👏 
just the language not working now

**Comment by brianteeman** [comment]
scrub that. languages working when I do what you said and comment those lines as well.

thanks for your work on his so far. awesome stuff

**Comment by brianteeman** [comment]
> However we still need to update Example pages to Bootstrap 5, and remove jquery from there.

Done #23

**Comment by Fedik** [comment]
> scrub that. languages working when I do what you said and comment those lines as well.

Probably we better remove that part from here, to avoid further confusion.
And will add to setup.js that will be with joomla plugin.

**Pull request merged**
