### PR TITLE
Added Dev environment with node

### PR DESCRIPTION
**Pull request by carcam**
To help others with #16 I have added a light http server which allows you to easily check your results while you are changing css and js files.

I hope this helps speed up a bit the development.

### CODE REVIEW

**Comment by brianteeman** [comment]
```
C:\htdocs\sa11y>npm run serve

> joomla-a11y-checker@1.0.0 serve
> light-server -b localhost -s ./ -w "src/**/* # npm run build # reload"

Error: listen EACCES: permission denied 127.0.0.1:4000
    at Server.setupListenHandle [as _listen2] (net.js:1301:21)
    at listenInCluster (net.js:1366:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1503:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:8) {
  code: 'EACCES',
  errno: -4092,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 4000
}

```

**Comment by carcam** [comment]
It seems an issue with windows powershell: 

https://superuser.com/questions/1437780/how-to-fix-listen-eacces-permission-denied-on-any-port

Can you please try port 8080 ?

**Comment by brianteeman** [comment]
Changing that line works
`    "serve": "light-server -b localhost --port 8080 -s ./ -w \"src/**/* # npm run build # reload\""
`

**Comment by carcam** [comment]
Peefect, will add the fix

**Comment by carcam** [comment]
I have fixed the port and updated testing instructions accordingly and added the reload thing ;)

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
