### PR TITLE
Remove Joomla translation override from main file

### PR DESCRIPTION
**Pull request by Fedik**
Remove Joomla translation override from main file

We better add it to plugin setup.js file.

### CODE REVIEW

**Comment by brianteeman** [comment]
> We better add it to plugin setup.js file.

Not sure I understand

**Comment by Fedik** [comment]
For Joomla plugin we will be need a setup.js (kind of that we have for tynimce) to set configuration and stuff.
We also can place current "language hack" there.

**Comment by brianteeman** [comment]
ok

**Comment by brianteeman** [comment]
actually why do we even need the hack?

**Comment by Fedik** [comment]
> actually why do we even need the hack?

To make translation from INI files, the idea was that translation for Joomla will come from plugin ini file.
And we can use `Joomla.Text._()`for translation.
Also with that hack we add prefix `'JOOMLA_A11Y_CHECKER_'` to all constants from `lang/en.js`.

So example constant `ALERT_CLOSE` become `JOOMLA_A11Y_CHECKER_ALERT_CLOSE`, and will be loaded from Plugin translations.

**Comment by dgrammatiko** [comment]
@Fedik you need to fix the conflicts here

**Comment by brianteeman** [comment]
closed ass fixed with #59

**Pull request closed without merging**
