### PR TITLE
Include tippy in to dist build

### PR DESCRIPTION
**Pull request by Fedik**
Include tippy in to dist build,
and update build.

Also renamed `dist/en.js` to `dist/en.umd.js` to avoid confusion with `src/en.js`

### CODE REVIEW

**Comment by brianteeman** [comment]
My gut feeling is not to include tippy in the build and to keep it as a dependency. Otherwise what would happen if the site already had tippy?

**Comment by Fedik** [comment]
Nothing will happen, 
The tippy here is "isolated" from outer world. So it will work even the site have older/newest tippy.

**Comment by Fedik** [comment]
As you and @bembelimen will decide 
I am okay with any way: or dependency or including

**Comment by dgrammatiko** [comment]
Both tippy and popper need to be done through Javascript imports, it's 2021...

**Comment by Fedik** [comment]
replaced by #51

**Pull request closed without merging**
