### PR TITLE
joomla style language strings

### PR DESCRIPTION
**Pull request by brianteeman**
still a work in progress.
need to do the strings with sprintf

### CODE REVIEW

**Comment by Fedik** [comment]
This will be need to re check,
Many syntax errors related to use of [Template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) 

https://github.com/joomla-projects/joomla-a11y-checker/blob/cc2574760b48681261fc552a86a0d478668fc553/src/js/sa11y.js#L126-L128

Example here no need to use  backticks for
```
aria-label="`${Sa11yLang._('JOOMLA_A11Y_CHECKER_MAIN_TOGGLE_LABEL')}`" 
```
Because whole text already inside backticks, should be just:
```
aria-label="${Sa11yLang._('JOOMLA_A11Y_CHECKER_MAIN_TOGGLE_LABEL')}" 
```

**Comment by brianteeman** [comment]
ok will fix that shortly

**Comment by brianteeman** [comment]
This block of code (that works in j3) is not working in j4

https://github.com/joomla/joomla-cms/blob/2e44061275b1ae4d7e1513ff879553a8f0037169/components/com_contact/src/View/Contact/HtmlView.php#L253-L264

**Comment by brianteeman** [comment]
fixed those for you

**Pull request merged**
