### PR TITLE
Refactoring: define module exports, build umd, fix much errors 

### PR DESCRIPTION
**Pull request by Fedik**
I have made `Sa11y` to be used as module, and updated build to generate `umd` wich we will use later in Joomla.
Made a `defaultOptions`, which can be overrided per instance.

Removed `sprintf`, and replaced with own code. 
~~This still need some to do, to replace all strings to use `%s` instead of `%(blabla)`.~~

Fixed much errors, probably there still many undefined because drop of `sa11y-english.js`, will fix them on the way.
Much translation related errors.

Instantiation is changed (look errors.html for example).

**For module**:
```html
<script type="module">
 import Sa11y from '../../src/js/sa11y.js';
 import EngSetting from '../../src/js/lang/en.js';

 // Set translations
 Sa11y.Lang.addI18n(EngSetting.strings);

 // Instantiate
 const checker = new Sa11y.Sa11y(EngSetting.options);
</script>
```
**For non module:**
```html
<script src="../../dist/js/joomla-a11y-checker.umd.js" defer></script>
<script src="../../dist/js/lang/en.js" defer></script>
<script>
  document.addEventListener('DOMContentLoaded', function() {
     // Set translations
     Sa11y.Lang.addI18n(Sa11yLangEn.strings);

     // Instantiate
     const checker = new Sa11y.Sa11y(Sa11yLangEn.options);
  });
</script>
```

Can test code by opening of docs/examples/errors.html 

Further steps is to continue fixing errors and start with replacing of jquery related code.
Update all example pages.

### CODE REVIEW

**Comment by Fedik** [comment]
Ping @bembelimen :)

**Comment by brianteeman** [comment]
> Removed sprintf, and replaced with own code.
This still need some to do, to replace all strings to use %s instead of %(blabla).

It was intentional not to use the meaningless %s

**Comment by Fedik** [comment]
Okay, then we can keep `%(blabla)`, it already works.
For me no big difference.

I think I will update all demo to use our code, to be able to see how our changes works.
Then we can merge this patch, and move on.

**Comment by brianteeman** [comment]
@fedik do you want me to merge this now or wait for the updated demo?

**Comment by Fedik** [comment]
> do you want me to merge this now or wait for the updated demo?

please wait, I will update demos, maybe some more little changes.
I try to finish this part in upcoming days,

**Comment by Fedik** [comment]
@brianteeman it can be merged.
I have updated all example to use our code, now we can see our mistakes :)

**Comment by brianteeman** [comment]
merged - thanks

**Pull request merged**
