### PR TITLE
Fix test link instructions in README

### PR DESCRIPTION
**Pull request by carcam**

### CODE REVIEW

**Comment by brianteeman** [comment]
did you intend to include the css changes

**Comment by carcam** [comment]
Actually I was saving them for another commit. I try to be clean and organized, but if you do not mind mixing them I can tell you I tested them and they work as they should.

**Comment by brianteeman** [comment]
can you remove the css please and we can deal that in its own pr please

**Comment by carcam** [comment]
@brianteeman sure I can!! It's fixed now.

Best!!

**Pull request merged**
